### ISSUE TITLE
Enable Bazaar automatic feeds from the community discussions

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/appsAway#102]
Hi @icub-tech-iit/code 

This is just to keep track of the fact that we still lack the availability of a REST API for the brand new GH discussions.
As a result, after the migration of issues to discussions in our community, the automatic publication of the feeds on Bazaar is unfortunately broken.

There's nothing we can actually do now unless waiting for GH to provide the REST, hopefully soon 🙏🏻

cc @traversaro @drdanz.

**Comment by vtikha** [comment]
Yes, as i mentioned we are planning to remove the announcement page as it is not useful to have it anymore, at least until the REST is available.

**Comment by pattacini** [comment]
The GraphQL (not REST then) API has been released today in beta.
Check it out at https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions.

cc @vtikha @AlexAntn @Nicogene

**Comment by pattacini** [comment]
Today, GitHub has also released webhooks that can be triggered by events related to discussions:
- https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#discussion
- https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#discussion_comment

To catch webhooks events we need an active server (with Sinatra it's quite easy to do that) so I don't know if webhooks are easier than GH actions.

**Comment by pattacini** [comment]
See https://github.com/robotology/community/pull/516.

**Comment by pattacini** [comment]
PR merged ✔️ 
We might consider [these activity](https://github.com/robotology/community/pull/516#issuecomment-871623502) for future possible improvements.
