### ISSUE TITLE
Create a new "How To" Bazaar section for iCubGenova04

### ISSUE THREAD

**Issue by giovannipizzolante** [icub-tech-iit/appsAway#126]
With @S-Dafarra,  we tried to edit the Bazaar page, but none of the sections seemed a good fit. It is possible to create a new "How to" section and copy and paste these very basic guidelines to start and stop the robot (https://github.com/dic-iit/lab-organisation/wiki/Use-iCub)?

**Comment by vtikha** [comment]
Thank you @giovannipizzolante and @S-Dafarra,  yes it is possibile. I have planned a meeting together to discuss about the specific requirements on Thursday the 22nd of April, and the outcome/decision/plan will be added in this issue.

**Comment by vtikha** [comment]
During our discussions and various interactions with @S-Dafarra @giovannipizzolante, we decided to go ahead with the use of `custom fields` that can be added by the user. The user can add multiple fields as one would in a wiki or an issue composed in markdown.  These customizable fields appear at the end of all the other sections, while in editing mode the customization appears as a new section which includes the possibility to add, modify or delete these newly added fields.

Here is a screenshot taking the example above:

<img width="575" alt="Screenshot 2021-05-05 at 16 10 59" src="https://user-images.githubusercontent.com/4537987/117155298-f1f8bf80-adbc-11eb-98aa-47624bb176f4.png">
