### ISSUE TITLE
iCubGenova09 robot does not appear in Robot-Bazaar Manager

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/appsAway#174]
The `iCubGenova09` is tracked in Robot Bazaar (see https://robot-bazaar.iit.it/robots/collection/robots/iCubGenova09) but for some reason it does not appear in Robot-Bazaar Manager.

cc @ilaria-carlini

**Comment by ilaria-carlini** [comment]
With @lauracavaliere we just fixed this issue [here](https://github.com/icub-tech-iit/code/commit/07d7685ee822a686dbe7f6abca3dbbba18b2a86a). You can find a brief description of what we did in the above-mentioned [issue](https://github.com/icub-tech-iit/code/issues/663#issuecomment-868279008) on `code` repository.

**Comment by pattacini** [comment]
Hi @ilaria-carlini, as a general remark, it'd be better to report a summary of what you did to solve the problem rather than posting links to private repositories that can't be visited by users who have not the permissions.

**Comment by ilaria-carlini** [comment]
Hi @pattacini, thank you for your suggestion. I just edited the comment.

**Comment by pattacini** [comment]
Thanks heaps @ilaria-carlini ✨
